[book]
authors = ["async fn fundamentals Members"]
language = "en"
multilingual = false
src = "."
title = "async fn fundamentals initiative"

[output.html]
no-section-label=true
git-repository-url="https://github.com/rust-lang/async-fundamentals-initiative"
edit-url-template="https://github.com/rust-lang/async-fundamentals-initiative/edit/master/{path}"
site-url="/async-fundamentals-initiative/"

[output.html.fold]
enable = true
level = 0

# TODO: enable once actions are configured
# [output.linkcheck]
# optional = true

[output.html.redirect]
"/roadmap/mvp.html" = "/roadmap/static_async_trait_mvp.html"
"/design-discussions/index.html" = "/roadmap.html"
"/design-discussions/static_async_trait.html" = "/roadmap/static_async_trait.html"
"/design-discussions/impl_trait_in_traits.html" = "/roadmap/impl_trait_in_traits.html"
"/design-discussions/dyn_async_trait.html" = "/roadmap/dyn_async_trait.html"
"/design-discussions/dyn_trait.html" = "/roadmap/dyn_trait.html"
"/design-discussions/async_drop.html" = "/roadmap/async_drop.html"
"/design-discussions/async_closures.html" = "/roadmap/async_closures.html"
"/explainer/phase_1.html" = "/archive/2021-phase_1.html"
"/explainer/phase_1_narrative.html" = "/archive/2021-phase_1_narrative.html"

# Clean up yml headers from e.g. HackMD docs.
[preprocessor.yml-header]
